### PR TITLE
MLST: swapping muscle for mafft add

### PR DESCRIPTION
**Pull request by alexweisberg**
I switched out using muscle for the MLST analysis to using MAFFT add to add to existing alignments which get concatenated together. In this new method, the user can add any number of individual gene sequences, up to the size of the dataset, rather than pre-concatenated genes in a specific order.
I also set it up so that each dataset of gene alignments has its own folder, that way datasets with overlapping genes but different taxa don't conflict. I did not add datasets for the Housekeeping genes and  Virulence genes as I don't have the original gene alignments. We will also have to change the help message on the MLST page so that it matches this new method.

### CODE REVIEW

**Comment by zkamvar** [comment]
I'm okay with this being merged if anyone else is okay with it.

**Comment by Tabima** [comment]
Not yet... I found out, by playing with the Agro-DB, that the new way lets us only have one query at a time (2 queries):

```
>recA
AGCAGCGAC....
>recA
AGCGAGCAG...
```

We should expect two queries, but we end up with a query and a NA:

screen shot 2015-06-04 at 10 55 03 pm

Alex, am I doing this the right way or am I missing something? If I am, I need to fix the multiple query stuff so it works!!

Thanks!!

**Comment by alexweisberg** [comment]
Hi Javier, 

You are correct in that it only allows one query at a time, that was how I got around the concatenated alignments as input. We would have to modify it so that the input would have a gene name and an isolate name so that genes and isolate sequences could match up ie something like “>isolate1|recA” or something along those lines.

Alex 

On June 4, 2015 at 7:59:08 PM, Javier F. Tabima (notifications@github.com) wrote:

Not yet... I found out, by playing with the Agro-DB, that the new way lets us only have one query at a time (2 queries):

> recA
> AGCAGCGAC....
> recA
> AGCGAGCAG...

We should expect two queries, but we end up with a query and a NA:

Alex, am I doing this the right way or am I missing something? If I am, I need to fix the multiple query stuff so it works!!

Thanks!!

**Comment by Tabima** [comment]
Awesome.

Here's a thought, though:

If we change the names by doing this:
_Input:_

```
>Query1|recA
AAAAACAGATATATA
>Query2|recA
AAAAACAGATATATA
>Query1|gyrB
AAAAACAGATATATA
```

and we fix it, then we will have to create a way where:
1). We match each of the genes to the alignment dataset independently per sample/query
2). We fill with gaps the absence of a gene (like, for gyrB in Query2)

or we decide to avoid all of this and make a disclaimer saying that "You should only use ONE SAMPLE" in this dataset. This, of course, will only apply to MLST-ID, and since the program doesn't take so long to run, its likely that people would do that.

What do you all think? Should we meet and discuss this?

**Comment by alexweisberg** [comment]
I’m fine with allowing just one query isolate, especially since it runs pretty quickly. The code would probably just have to be modified to allow only one entry per gene so that the situation where you tested with multiple GyrB’s doesnt result in a new sequence called NA.

On June 4, 2015 at 9:42:23 PM, Javier F. Tabima (notifications@github.com) wrote:

Awesome.

Here's a thought, though:

If we change the names by doing this:
Input:

> Query1|recA
> AAAAACAGATATATA
> Query2|recA
> AAAAACAGATATATA
> Query1|gyrB
> AAAAACAGATATATA

and we fix it, then we will have to create a way where:
1). We match each of the genes to the alignment dataset independently per sample/query
2). We fill with gaps the absence of a gene (like, for gyrB in Query2)

or we decide to avoid all of this and make a disclaimer saying that "You should only use ONE SAMPLE" in this dataset. This, of course, will only apply to MLST-ID, and since the program doesn't take so long to run, its likely that people would do that.

What do you all think? Should we meet and discuss this?

**Comment by Tabima** [comment]
Cool, I think that's the best way to do it.

Taking all of that on account:
- We don't need to add the datasets for the Housekeeping genes and Virulence genes as the help page explains well with one is which, and your method creates a concatenated alignment for any mix-and-match set of genes the user wants to use.
- I'll fix the help message on the MLST page so that it matches the new method ASAP.

If you are fine with this, I'll just merge it!

Thanks again for all your help.

**Comment by alexweisberg** [comment]
No problem! That sounds good to me. I just want to point out that as it is now, the user can mix and match within a gene set, but not across them. ie they can’t use gyrB and 16S the way it is coded currently. I set it up so that each gene set is stored in it’s own folder, that way two different gene datasets can have the same gene (such as gyrB) but with different taxa.

On June 4, 2015 at 10:01:14 PM, Javier F. Tabima (notifications@github.com) wrote:

Cool, I think that's the best way to do it.

Taking all of that on account:

We don't need to add the datasets for the Housekeeping genes and Virulence genes as the help page explains well with one is which, and your method creates a concatenated alignment for any mix-and-match set of genes the user wants to use.

I'll fix the help message on the MLST page so that it matches the new method ASAP.

If you are fine with this, I'll just merge it!

Thanks again for all your help.

**Pull request merged**
